(async()=>{
const list=await fetch('manifest.json').then(r=>r.json());
const ids=['kicker','title','body','cta','signature'];const $=id=>document.getElementById(id);let current=null,source='';const ns='http://www.w3.org/2000/svg';
function options(){const items=list.filter(m=>m.platform===$('platform').value&&m.lang===$('language').value);$('model').replaceChildren(...items.map(m=>{const o=document.createElement('option');o.value=m.id;o.textContent=m.id.replaceAll('-',' ');return o;}));if(!items.length){$('language').value='fr';return options();}return load();}
async function load(){current=list.find(m=>m.platform===$('platform').value&&m.lang===$('language').value&&m.id===$('model').value);if(!current)return;source=await fetch(current.svg).then(r=>r.text());$('preview').innerHTML=source;await document.fonts.ready;ids.forEach(id=>{$(id).value=current[id]||'';$(id).disabled=!$('preview').querySelector(`[data-field="${id}"]`);});const photo=!!$('preview').querySelector('[data-photo]');$('photo').disabled=!photo;$('reset-photo').disabled=!photo;$('photo').value='';$('png').href=current.png;$('info').textContent=`${current.width} × ${current.height} px · ${current.lang.toUpperCase()} · Textes, couleurs et éléments SVG modifiables. Les zones de sécurité sont des recommandations de création ; elles ne garantissent pas tous les recadrages de l’application.`;render();}
function wrap(value,element){const width=+element.dataset.width,size=+element.dataset.size;const style=getComputedStyle(element);const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');ctx.font=`${style.fontWeight} ${size}px ${style.fontFamily}`;const lines=[];value.split('\n').forEach(paragraph=>{let line='';paragraph.split(/\s+/).filter(Boolean).forEach(word=>{const attempt=(line+' '+word).trim();if(ctx.measureText(attempt).width>width&&line){lines.push(line);line=word;}else line=attempt;});if(line)lines.push(line);});return lines;}
function render(){let long=false;ids.forEach(id=>{const element=$('preview').querySelector(`[data-field="${id}"]`);if(!element)return;const lines=wrap($(id).value,element);if(lines.length>+element.dataset.lines)long=true;const x=element.getAttribute('x'),y=+element.getAttribute('y'),lh=+element.dataset.lh;element.replaceChildren(...lines.map((line,n)=>{const span=document.createElementNS(ns,'tspan');span.setAttribute('x',x);span.setAttribute('y',y+n*lh);span.textContent=line;return span;}));});$('warning').textContent=long?'Texte trop long : raccourcissez-le pour conserver la mise en page.':'';$('download').disabled=long;const svg=$('preview').querySelector('svg');svg.setAttribute('aria-label',$('title').value||current.brand);svg.querySelector('#safe-overlay')?.remove();if($('safe').checked&&current.safe){const s=current.safe,r=document.createElementNS(ns,'rect');r.id='safe-overlay';Object.entries({x:s.x,y:s.y,width:s.width,height:s.height,fill:'none',stroke:'#db4437','stroke-width':3,'stroke-dasharray':'14 9','pointer-events':'none'}).forEach(([k,v])=>r.setAttribute(k,v));svg.append(r);}}
function download(filename,data,type){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('download').addEventListener('click',()=>{const clone=$('preview').querySelector('svg').cloneNode(true);clone.querySelector('#safe-overlay')?.remove();download(`${current.platform}-${current.id}-${current.lang}.svg`,new XMLSerializer().serializeToString(clone),'image/svg+xml');});
$('save-json').addEventListener('click',()=>download(`${current.id}-${current.lang}.json`,JSON.stringify({...current,...Object.fromEntries(ids.map(id=>[id,$(id).value]))},null,2),'application/json'));
$('platform').addEventListener('change',options);$('language').addEventListener('change',options);$('model').addEventListener('change',load);ids.forEach(id=>$(id).addEventListener('input',render));$('safe').addEventListener('change',render);
$('photo').addEventListener('change',()=>{const file=$('photo').files[0];if(!file)return;const group=$('preview').querySelector('[data-photo]');const original=group.getBBox();const reader=new FileReader();reader.onload=()=>{group.replaceChildren();const im=document.createElementNS(ns,'image');im.setAttribute('x',0);im.setAttribute('y',0);im.setAttribute('width',original.width);im.setAttribute('height',original.height);im.setAttribute('preserveAspectRatio',$('photo-position').value);im.setAttribute('href',reader.result);group.append(im);};reader.readAsDataURL(file);});$('reset-photo').addEventListener('click',()=>{const old=new DOMParser().parseFromString(source,'image/svg+xml').querySelector('[data-photo]');const group=$('preview').querySelector('[data-photo]');if(old&&group)group.replaceWith(document.importNode(old,true));$('photo').value='';});$('photo-position').addEventListener('change',()=>$('preview').querySelector('[data-photo] image')?.setAttribute('preserveAspectRatio',$('photo-position').value));
$('load-json').addEventListener('change',async()=>{try{const file=$('load-json').files[0];if(!file)return;const data=JSON.parse(await file.text());if(!list.some(m=>m.id===data.id&&m.platform===data.platform&&m.lang===data.lang))throw Error('unknown');$('platform').value=data.platform;$('language').value=data.lang;await options();$('model').value=data.id;await load();ids.forEach(id=>{if(typeof data[id]==='string')$(id).value=data[id];});render();}catch{$('warning').textContent='Ce fichier ne correspond pas à un modèle de ce kit.';}});
await options();
})().catch(()=>{document.getElementById('warning').textContent='Ouvrez cet éditeur avec le serveur local indiqué dans le guide.';});
