import json,pathlib
R=pathlib.Path(__file__).resolve().parent
models=[]
def add(platform,key,format,fr,en,theme='ivory',kind='standard',photo=False):
 for lang,value in [('fr',fr),('en',en)]:
  kicker,title,body,cta=value
  models.append(dict(id=key,platform=platform,lang=lang,format=format,theme=theme,kind=kind,photo=photo,kicker=kicker,title=title,body=body,cta=cta,brand='Valérie Migueres',signature='Un espace pour avancer' if lang=='fr' else 'Space to move forward'))
add('instagram','pedagogie','post',('COMPRENDRE · EXAMENS','Quand la pression monte.','Avant un examen, tout peut sembler urgent. Faites une pause pour distinguer ce qui dépend de vous et choisir une prochaine étape réaliste.','Enregistrer ce repère'),('UNDERSTANDING · EXAMS','When pressure builds.','Before an exam, everything can feel urgent. Pause to notice what is within your control and choose one realistic next step.','Save this reminder'),theme='sage')
slides=[
(('01 / 04 · SURCHARGE MENTALE','Tout porter, tout le temps ?','Il arrive que les tâches, les attentes et les pensées s’accumulent. Prenons un peu de recul.','Faire défiler →'),('01 / 04 · MENTAL OVERLOAD','Carrying it all?','Tasks, expectations and thoughts can pile up. Let’s take a step back.','Swipe to explore →')),
(('02 / 04 · METTRE DES MOTS','Qu’est-ce qui pèse ?','Notez ce qui occupe votre esprit. Distinguez les urgences réelles, les attentes des autres et vos propres besoins.','Un repère, à votre rythme'),('02 / 04 · PUT IT INTO WORDS','What feels heavy?','Write down what is on your mind. Separate genuine priorities, other people’s expectations and your own needs.','One step, at your own pace')),
(('03 / 04 · CLARIFIER','Une chose à la fois.','Quel petit ajustement serait possible aujourd’hui ? Une limite, une pause ou une demande d’aide peut ouvrir une piste.','Choisir une étape réaliste'),('03 / 04 · FIND CLARITY','One thing at a time.','What small adjustment might be possible today? A boundary, a break or asking for support can open a way forward.','Choose one realistic step')),
(('04 / 04 · ALLER PLUS LOIN','Un espace pour faire le point.','L’accompagnement permet d’explorer vos besoins, vos ressources et les prochaines étapes qui vous conviennent.','Découvrir l’accompagnement'),('04 / 04 · EXPLORE FURTHER','Space to take stock.','Support offers room to explore your needs, resources and next steps that feel right for you.','Explore the support'))]
for n,(fr,en) in enumerate(slides):add('instagram',f'carrousel-{n+1:02}','post',fr,en,theme='green' if n in (0,3) else 'ivory')
add('instagram','accompagnement','post',('ACCOMPAGNEMENT · NICE','Une nouvelle direction professionnelle.','Reconversion, prise de poste ou bilan de compétences : faire le point sur vos aspirations et ce qui compte pour vous.','Découvrir l’accompagnement'),('SUPPORT · NICE','A new career direction.','Career change, a new role or a French career review — bilan de compétences: reflect on your aspirations and priorities.','Explore this support'),theme='sand',photo=True)
add('instagram','faq','post',('VOTRE QUESTION','Faut-il déjà savoir ce dont j’ai besoin ?','Vous pouvez venir avec une question ou une situation difficile à nommer. Nous prendrons le temps de clarifier votre demande.','Découvrir mon approche'),('YOUR QUESTION','Do I need to know what I need?','You can begin with a question or a situation that is hard to put into words. We take time to understand your enquiry.','Explore my approach'))
add('instagram','reel','portrait',('UNE QUESTION · UN REPÈRE','Retrouver confiance.','Par où commencer ?','Découvrir la vidéo'),('ONE QUESTION · ONE PERSPECTIVE','Build your confidence.','Where could you begin?','Watch the video'),theme='green',kind='reel',photo=True)
add('instagram','story','portrait',('ACCOMPAGNEMENT · NICE','Faire le point, simplement.','Stress, doute ou transition : un premier message peut ouvrir la conversation.','Me contacter'),('SUPPORT · NICE','Take stock, simply.','Stress, uncertainty or change: a first message can open a conversation.','Get in touch'),theme='sage',kind='story')
for key,fr,en in [('a-propos','À propos','About'),('approche','Approche','Approach'),('seances','Séances','Sessions'),('cabinet','Cabinet','Practice'),('faq','FAQ','FAQ'),('contact','Contact','Contact')]:
 add('instagram','a-la-une-'+key,'square',('VM',fr,'',''),('VM',en,'',''),theme='green',kind='highlight')
add('whatsapp','presentation','portrait',('VALÉRIE MIGUERES · NICE','Un espace pour avancer.','Un accompagnement personnel et professionnel pour prendre du recul dans les périodes de stress, de doute et de transition.','Découvrir les accompagnements'),('VALÉRIE MIGUERES · NICE','Space to move forward.','Personal and professional support to gain perspective through stress, uncertainty and change.','Explore areas of support'),theme='green',kind='story',photo=True)
add('whatsapp','conseil','portrait',('UN REPÈRE POUR AUJOURD’HUI','Une priorité. Une prochaine étape.','Quand tout semble urgent, prenez un moment pour identifier ce qui compte aujourd’hui. Vous pouvez commencer petit.','À votre rythme'),('A THOUGHT FOR TODAY','One priority. One next step.','When everything feels urgent, pause to consider what matters today. A small beginning is enough.','At your own pace'),theme='ivory',kind='story')
add('whatsapp','invitation','portrait',('PRENDRE CONTACT','Vous souhaitez faire le point ?','Quelques mots sur votre demande suffisent. Évitez de partager des informations médicales ou sensibles ici.','Demander un rendez-vous'),('GET IN TOUCH','Would you like to take stock?','A few words about your enquiry are enough. Please avoid sharing medical or sensitive information here.','Request an appointment'),theme='sage',kind='story')
add('whatsapp','accompagnements','post',('PERSONNEL & PROFESSIONNEL · NICE','Ce qui vous amène.','Confiance et équilibre\nTransitions personnelles\nÉtudes et examens\nÉvolution professionnelle\nAteliers en entreprise','Découvrir les accompagnements'),('PERSONAL & PROFESSIONAL · NICE','What brings you here.','Confidence and balance\nLife transitions\nStudies and exams\nCareer development\nWorkplace workshops','Explore areas of support'),theme='sand')
add('youtube','banniere','banner',('PERSONNEL & PROFESSIONNEL · NICE','Valérie Migueres','Un espace pour avancer',''),('PERSONAL & PROFESSIONAL · NICE','Valérie Migueres','Space to move forward',''),theme='green',kind='banner')
for key,fr,en in [('confiance','Confiance : par où commencer ?','Confidence: where to begin?'),('examens','Examens : quand la pression monte','Exams: when pressure builds'),('reconversion','Reconversion : faire le point','Career change: take stock')]:
 add('youtube','miniature-'+key,'thumbnail',('UN REPÈRE · VALÉRIE MIGUERES',fr,'',''),('ONE PERSPECTIVE · VALÉRIE MIGUERES',en,'',''),theme='green' if key=='confiance' else 'sand' if key=='examens' else 'sage',kind='thumbnail',photo=True)
add('youtube','titre-ecran','video',('VALÉRIE MIGUERES','Comprendre la surcharge mentale.','Un repère pour faire le point.',''),('VALÉRIE MIGUERES','Understanding mental overload.','A perspective to help you take stock.',''),theme='ivory',kind='title')
add('youtube','intro','video',('','Valérie Migueres','Un espace pour avancer',''),('','Valérie Migueres','Space to move forward',''),theme='green',kind='intro')
add('youtube','fin','video',('POURSUIVRE LA RÉFLEXION','Un espace pour avancer.','Découvrez une autre vidéo ou prenez contact via les liens de la description.','Merci de votre attention'),('KEEP EXPLORING','Space to move forward.','Explore another video or get in touch using the links in the description.','Thank you for watching'),theme='ivory',kind='end')
(R/'content.json').write_text(json.dumps(models,ensure_ascii=False,indent=2)+'\n')
print(len(models),'modèles bilingues')
